version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: $project_slug
    environment:
      - APP_ENV=prod
    restart: always
    networks:
      - app-network

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: $project_slug-tunnel
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    restart: always
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
