apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bmdr-app
  namespace: bmdr-setup
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app.bmdr.io
    secretName: bmdr-app-tls
  rules:
  - host: app.bmdr.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bmdr-app
            port:
              number: 80
