apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bmdr-setup

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/bmdr-bot/bmdr-setup
    newTag: latest

commonLabels:
  app.kubernetes.io/name: bmdr-app
  app.kubernetes.io/part-of: bmdr-setup